apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kafka-init
          image: bitnamilegacy/kafka:3.7
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -c
            - |
              set -e
              for topic in clicks.raw clicks.dlq; do
                /opt/bitnami/kafka/bin/kafka-topics.sh \
                  --bootstrap-server kafka:9092 \
                  --create --if-not-exists --topic "$topic" \
                  --partitions 3 --replication-factor 1
              done
