apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |-
{{ .Files.Get "files/postgres-init.sql" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-init
data:
  init.sql: |-
{{ .Files.Get "files/clickhouse-init.sql" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
{{- range $k, $v := .Values.api.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
